# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mr5a4xW6fy3R5jD_lkQ9McP6kKr21xqW
"""

x=input()
y=int(input())
Num_list=x.split()
dict1={}
final_list=[]


for a,b in enumerate(Num_list):
     dict1[int(b)]=int(a)
for i in dict1.keys():
     total=y-i
     if total in dict1 and total!=0:
           final=dict1[i]+dict1[total]
           if final not in final_list:
              final_list.append(final)
     if total==0:
            final_list.append(dict1[i])

sorted_num=sorted(final_list)
if not final_list:
    print("Not Found!")
else:
   for s in sorted_num:
       print(s)