# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mr5a4xW6fy3R5jD_lkQ9McP6kKr21xqW
"""

string=input()
list_string=[]
my_list=[]
k=0
for i in string:
    list_string.append(i)

for j in list_string:
    if j=="@":
        k+=1
        my_list.append("@")
    elif j=="#" and k>0:
        k-=1
    else:
        my_list.append(j)
new_string=""
for s in my_list:
    new_string+=s


import re
new_string1 = new_string.split()
new_string2 = " ".join(new_string1)
new_string3 = re.sub(r'\\n' , '\n' , new_string2)
print("Formatted Text: ",new_string3)