# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hblta10uIRixkn8AfQRJCbRbOzrH2DRA
"""

x = int(input())
k = 0
outputs = []

while k!=x :
    k+=1
    email = input()
    seperated = email.split("@")
    a = "".join(seperated[1:])
    outputs.append(a)

newNums = set(outputs)
sortedSet = sorted(newNums)
for i in sortedSet :
    print(i)