# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nml5PdlMx4jHDf1ilbmA90xD7SjWVIiI
"""

x = input()
list_string = x.split(" ")
list_string.sort(key = lambda i : int(i[1:]))
for char in list_string :
    print(char[0] , end="")