# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-tWqshKw_uxqs1JplIrOy33T1kLcQmTP
"""

a = int(input())
b = int(input())
result = bin(a ^ b)
c = result.count('1')
print (c)