# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199PWxgrMfpHUapj5MT_HmVMkNhDpVgxN
"""

def prime(x) :
    if x<2 :
        return False
    for y in  range (2,int(x**0.5)+1) :
        if x%y == 0 :
            return False
    return True
a , b = map (int,input().split())
count = 0
if (a<=b) :
 for x in range (a,b+1) :
    if prime(x):
        count+=1
 print ("main order - amount: ",count)
else :
 for x in range (b,a+1) :
    if prime(x):
        count+=1
 print ("reverse order - amount: ",count)