# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A_OAb0q8WPxfTHlsCbi5NMcOKCUOT9N4
"""

def t_bin(n):
    return "{:032b}".format(int(n))
x = int(input())
y = int(input())
k = int(input())
right = t_bin(x)
left = t_bin(y)
total = str(left)+str(right)
listmehman=[]
for i in range(k):
    tmp=int(input())
    if total[-tmp-1]=="1":
        listmehman.append("yes")
    elif total[-tmp-1]=="0":
        listmehman.append("no")
for a in range (len(listmehman)):
    print(listmehman[a])