# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Z-TQYWvmPamyRAew0C_hkQF3qP_7lU2
"""

print ('Hello Python')