# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpH1Q1aNoSDTwwIAefmCIknR0C1Hvl1c
"""

x = input()
a = []
k = 0

def gcd(a,b) :
    while b != 0 :
        a , b = b , a%b
    return a

def lcd(a,b) :
    return abs(a*b)//gcd(a,b)

if x != "sum" and x != "average" and x != "gcd" and x != "lcd" and x != "max" and x != "min" :
  print("Invalid command")

else :
  while True :
    b = input()
    k += 1
    if b != "end" :
        a.append(int(b))
        if x == "sum" :
           final = sum(a)

        elif x == "average" :
           final = sum(a)/k
           final = round(final, 2)

        elif x == "gcd" :
            for i in a :
               while len(a) != 1 :
                   final = gcd(a[0] , a[1])
                   n1 = a[0]
                   n2 = a[1]
                   a.remove(n1)
                   a.remove(n2)
                   a.append(final)
            final = a[0]

        elif x == "lcd" :
            for j in a :
                while len(a) != 1 :
                    final = lcd(a[0] , a[1])
                    n1 = a[0]
                    n2 = a[1]
                    a.remove(n1)
                    a.remove(n2)
                    a.append(final)
            final = a[0]

        elif x == "min" :
            final = min(a)

        elif x == "max" :
            final = max(a)

    else :
        break
  print(final)