# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Xfs4cg-MRBybQHdmxKOUJ61BK-KsAYp
"""

n = int(input())

if n == 1 :
 print("1")

elif n == 2 :
 print("1")
 print("1 1")

else:
 print("1")
 print("1 1")
 a = [1, 1]

 while len(a) != n :
  x = [1]
  for i in range (len(a)-1) :
      x.append(a[i+1] + a[i])

  x.append(1)
  print()

  for i in x :
      print(i, end= ' ')
  print()
  a = []
  for j in x :
   a.append(j)